### ISSUE TITLE
Mysqldump not recognized.

### ISSUE THREAD

**Issue by Santana1053** [snapcreek/duplicator#24] opened 2017-11-07 17:58 UTC
Ubuntu 14.04.5 LTS (GNU/Linux 4.9.50-x86_64-linode86 x86_64)
mysqldump  Ver 10.13 Distrib 5.6.38, for Linux (x86_64)
```
which mysqldump
  /usr/bin/mysqldump
```
In the duplicator settings I see this warning:
```
 Mysqldump was not found at its default location or the location provided. Please enter a custom path to a valid location where mysqldump can run. If the problem persist contact your host or server administrator. See the host list for reliable access to mysqldump.
```
When I try to set the path manually I get this error:
```
The custom path provided is not recognized as a valid mysqldump file:
'/usr/bin/mysqldump'
```

**Comment by Santana1053** [comment] 2017-12-18 22:47
Hello?

**Comment by lifeinthegrid** [comment] 2017-12-19 01:02
Hey Santana1053,

If you want to submit a <a href='https://snapscreek.com/ticket'>support ticket</a> for this issue I can have a closer look at your setup.  Please provide a link to this thread when submitting the ticket.

Thanks~

**Comment by Magi1053** [comment] 2017-12-19 03:08
Looks like the site you just linked me is down

**Comment by lifeinthegrid** [comment] 2017-12-19 03:20
Ugg.. bad url give it a try again!

**Comment by jkahrs** [comment] 2018-07-06 08:45
I think I'm seeing something similar here. The problem is that the path is checked via file_exists() [here](https://github.com/lifeinthegrid/duplicator/blob/3b20f5ee6660928e302cd6eac5409c6f75a7913d/classes/class.db.php#L170). file_exists() however will return false on paths restricted by open_basedir even if the path itself can be executed via shell_exec()

**Comment by mklengel** [comment] 2018-07-09 10:20
I have the same problem - mysqldump exists but is not recognized.
What about disabling the check if there is no quick solution available?

**Comment by lifeinthegrid** [comment] 2018-07-11 15:13
Thanks for the feedback we will add this to our backlog of items to investigate.   In the meantime, if you have any code snippets that work for you please post...  Thanks

**Comment by jkahrs** [comment] 2018-07-13 16:05
Update: I have added https://github.com/lifeinthegrid/duplicator/pull/26 for review/testing

**Comment by lifeinthegrid** [comment] 2018-07-18 02:29
The changes from jkahrs have now been merged into the master.

If everyone on this thread can give the developer version a try it should have the updates for your issue.  The very latest version (1.2.41) can be found by following these instructions:

	- <a href="https://downloads.wordpress.org/plugin/duplicator.zip">Download Developer Version</a>
	- Uninstall your current version and install this one.
	
Let me know if this solves your issue~

Thanks

**Comment by jkahrs** [comment] 2018-07-18 09:23
Hi,

I think the current change is missing my changes on views/settings/packages.php where the same is_file check is performed [here](https://github.com/lifeinthegrid/duplicator/blob/1cde7f599cfb49812d03601e3330fed6b94b193a/views/settings/packages.php#L21) to later store the form value into DUP_Settings [here](https://github.com/lifeinthegrid/duplicator/blob/1cde7f599cfb49812d03601e3330fed6b94b193a/views/settings/packages.php#L27). This leads to [this](https://github.com/lifeinthegrid/duplicator/blob/1cde7f599cfb49812d03601e3330fed6b94b193a/classes/class.db.php#L122) being empty later.

I'm not sure where the mysqldump binary is used later (apart from classes/class.db.php). Potentially the check from views/settings/packages.php can be removed?

**Comment by lifeinthegrid** [comment] 2018-07-18 23:16
I see, thanks for the details!   I have committed another change both here and to the WP repro link above, please let me know if this helps~

Thanks

**Comment by jkahrs** [comment] 2018-07-19 07:45
Thank you for the quick update. Now the custom mysqldump path seems to be working for me 🎉

**Comment by lifeinthegrid** [comment] 2018-07-19 23:50
Excellent thanks for the update!  Hopefully, I can get more feedback from the other users.

Cheers~

**Comment by KroshkaMu** [comment] 2018-08-14 11:10
I just had the same problem. The developer version works properly. Thanks!

**Comment by lifeinthegrid** [comment] 2018-10-16 14:56
This issue looks to have been fixed.  Please submit new issue if the problem becomes and issue again.

**Comment by lifeinthegrid** [comment] 2020-02-06 18:25
During a refactor effort this issue was reintroduced if any of the users in this thread can help test the master line here; https://github.com/snapcreek/duplicator/archive/master.zip    We can get the patch out asap.   Thanks!

**Closed** 2020-03-14 17:30 UTC
